apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ecommerce-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: nestjs-ecommerce/auth-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: AUTH_DB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_DB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_EXPIRATION
        - name: AUTH_PORT
          value: "3004"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z mongodb-auth 27017; do echo waiting for mongodb-auth; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ecommerce-microservices
spec:
  selector:
    app: auth-service
  ports:
  - port: 3004
    targetPort: 3004
  type: ClusterIP