apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: ecommerce-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: nestjs-ecommerce/customer-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: CUSTOMER_DB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CUSTOMER_DB_URI
        - name: CUSTOMER_PORT
          value: "3001"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z mongodb-customer 27017; do echo waiting for mongodb-customer; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: ecommerce-microservices
spec:
  selector:
    app: customer-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP